services:
  couchbase:
    container_name: cb
    build:
      context: .
      dockerfile: dockerfiles/couchbase/Dockerfile
    env_file:
      - ./.env
    ports:
      - '8091-8096:8091-8096'
      - '11210-11211:11210-11211'
    volumes:
      - ./volumes/couchbase:/opt/couchbase/var
    networks:
      todo-list-network:
        ipv4_address: 10.5.0.2

networks:
  todo-list-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/8
